services:
  proxy:
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - lab
  backend:
    build: ./backend
    expose:
      - "8080"
    networks:
      - lab
  frontend:
    build: ./frontend
    expose:
      - "3000"
    networks:
      - lab
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: joat
      POSTGRES_USER: joat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /root/postgres_data:/var/lib/postgresql
    expose:
      - "5432"
    networks:
      - lab 

networks:
  lab:
    driver: bridge
