server {
    listen 443 ssl;
    server_name derdis.dev www.derdis.dev;

    ssl_certificate /etc/letsencrypt/live/derdis.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/derdis.dev/privkey.pem;

    location / {
        add_header Content-Type text/plain;
        return 200 "nginx is doing nginx-things";
    }

    location /api {
        proxy_pass http://backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name derdis.dev;

    return 301 https://$host$request_uri;
}
